ar3:
    hardware_interface:
        joint_offsets: # degrees, will be zero since offsets will be don in the controller
            joint_1: 0.0 #-170.0 # default -170.0
            joint_2: 0.0 #-39.6 # default -39.6
            joint_3: 0.0 # default 0.0
            joint_4: 0.0 #-164.5 # default -164.5
            joint_5: 0.0 #-104.5 # default -104.15
            joint_6: 0.0 #-148.1 # default -148.1
